version: '2'
services:
  booma-app:
    image: booma
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://booma-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=booma
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8181:8181
  booma-mongodb:
    extends:
      file: mongodb.yml
      service: booma-mongodb
